export const tags = {
  featureTypeName: "Name",
  title: "Title",
  abstract: "Abstract",
  defaultCRS: "DefaultCRS",
  lowerCorner: "LowerCorner",
  upperCorner: "UpperCorner",
  serviceType: "ServiceType",
  serviceTypeVersion: "ServiceTypeVersion",
  fees: "Fees",
  accessConstraints: "AccessConstraints",
  keywords: "Keywords",
  acceptVersions: '[name="AcceptVersions"]',
  providerName: "ProviderName",
  serviceContact: "ServiceContact",
  serviceProvider: "ServiceProvider",
  operation: "Operation",
  operationMethod: "name",
  featureType: "FeatureType",
  function: "Function",
  complexType: "complexType",
  sequence: "sequence",
  xLinkHRef: "xlink:href",
  name: "name",
  type: "type",
  member: "member"
};
