import globalConsts from '../config';
import consts from './constants';

const initialState = {
    url: '',
    version: globalConsts.versions[0],
    request: globalConsts.requests[0],
    service: 'WFS',
    typename: '',
    typenames: [],
    valueReference: '',
    valueReferences: consts.valueReferences,
    xmlNamespaces: {},
    wfsRequest: '',
    wfsResponse: '',
    getCapResp: '',
    descFeatTypeResp: '',
    getPropValResp: '',
    getPropValFiltResp: '',
    sortBy: 'ASC',
    errors: {
        url: ''
    },
    selectedTypValueRef: '',
    valueCount: '',
    minValue: '',
    maxValue: '',
    numericValue: '',
    showNumericValue: false,
    nonNumericValue: [],
    showNonNumericValue: false,
    filterValueCount: '',
    compOper: '',
    lowerValue: '',
    upperValue: '',
    addSortBy: consts.addSortBy,
    wfsFilterRequest: '',
    wfsFilterResponse: '',
    getGetCapTime: 0,
    postGetCapTime: 0,
    getGetCapNumber: 0,
    postGetCapNumber: 0,
    getDescFeatTypeTime: 0,
    postDescFeatTypeTime: 0,
    getDescFeatTypeNumber: 0,
    postDescFeatTypeNumber: 0,
    getGetPropValTime: 0,
    postGetPropValTime: 0,
    getGetPropValNumber: 0,
    postGetPropValNumber: 0,
    getGetPropValFiltTime: 0,
    postGetPropValFiltTime: 0,
    getGetPropValFiltNumber: 0,
    postGetPropValFiltNumber: 0,
    attrValues: [],
    isModalOpen: false,
    modalOperation: 'normal',
    getRequestClicked: false,
    postRequestClicked: false,
    getFilterRequestClicked: false,
    postFilterRequestClicked: false
};

export default initialState;
