export default {
    SET_URL: 'SET_URL',
    SET_VERSION: 'SET_VERSION',
    SET_REQUEST: 'SET_REQUEST',
    SET_TYPENAME: 'SET_TYPENAME',
    SET_TYPENAMES: 'SET_TYPENAMES',
    SET_WFS_REQUEST: 'SET_WFS_REQUEST',
    SET_WFS_RESPONSE: 'SET_WFS_RESPONSE',
    SET_GET_CAP_RESPONSE: 'SET_GET_CAP_RESPONSE',
    RESET: 'RESET'
};
