export default {
    SET_URL: 'SET_URL',
    SET_VERSION: 'SET_VERSION',
    SET_REQUEST: 'SET_REQUEST',
    SET_TYPENAME: 'SET_TYPENAME',
    SET_VALUE_REFERENCE: 'SET_VALUE_REFERENCE',
    SET_WFS_REQUEST: 'SET_WFS_REQUEST',
    SET_WFS_RESPONSE: 'SET_WFS_RESPONSE',
    SET_GET_CAP_RESPONSE: 'SET_GET_CAP_RESPONSE',
    SET_DESC_FEAT_TYPE_RESP: 'SET_DESC_FEAT_TYPE_RESP',
    RESET: 'RESET'
};
